name: Update EPG Daily

on:
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # 这里升级为 v4

      - name: Set up Python
        uses: actions/setup-python@v5 # 这里升级为 v5
        with:
          python-version: '3.10'

      - name: Run EPG generator
        run: python generate_epg.py

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add epg.xml
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto update epg.xml" && git push)
